avoid dependency to atl, problaby not available with mingw, because of
In file included from ../src/NppIO.cpp:36:0:
../src/WinControls/ReadDirectoryChanges/ReadDirectoryChanges.h:46:21: fatal error: atlbase.h: No such file or directory
compilation terminated.
makefile:260: recipe for target '../src/NppIO.o' failed
mingw32-make: *** [../src/NppIO.o] Error 1
Command exited with code 2