avoid linker issue due to missing lib dbghelp for ImageNtHeader
/IDAllocator.o ../src/MISC/Process/Processus.o ../src/MISC/RegExt/regExtDlg.o resources.res -lcomdlg32 -lcomctl32 -lgdi32 -lole32 -loleacc -lshell32 -lshlwapi -o ../bin/NotepadPP.exe
../src/MISC/PluginsManager/PluginsManager.o:PluginsManager.cpp:(.text+0x3ad): undefined reference to `_imp__ImageNtHeader@4'
collect2.exe: error: ld returned 1 exit status
makefile:257: recipe for target '../bin/NotepadPP.exe' failed
mingw32-make: *** [../bin/NotepadPP.exe] Error 1
Command exited with code 2